package poly.cinema.ui.manager;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import poly.cinema.dao.LoaiGheDAO;
import poly.cinema.dao.impl.LoaiGheDAOImpl;
import poly.cinema.entity.LoaiGhe;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author BA HAO
 */
public class LoaiGheJpanel extends javax.swing.JPanel implements LoaiGheController {

    /**
     * Creates new form LoaiGhe
     */
    public LoaiGheJpanel() {
        initComponents();
        init();
    }

    private void init() {
        open();
        tblBillDetaills.getSelectionModel().addListSelectionListener(e -> {
            int row = tblBillDetaills.getSelectedRow();
            if (row >= 0 && row < list.size()) {
                moveTo(row);
            }
        });
//        btnThem.addActionListener(e -> create());
//        btnSua.addActionListener(e -> update());
//        btnXoa.addActionListener(e -> delete());
//        btnNhapMoi.addActionListener(e -> clear());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBillDetaills = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaGhe = new javax.swing.JTextField();
        txtPhuPhi = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnNhapMoi = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1110, 720));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setText("LOẠI GHẾ");

        tblBillDetaills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã ghế", "Phụ phí"
            }
        ));
        tblBillDetaills.setRowHeight(25);
        tblBillDetaills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBillDetaillsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBillDetaills);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mã ghế ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Phụ phí");

        btnSua.setText("SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnNhapMoi.setText("NHẬP  MỚI");
        btnNhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapMoiActionPerformed(evt);
            }
        });

        btnXoa1.setText("XÓA");
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(481, 481, 481)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhuPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnNhapMoi)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhuPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhapMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1116, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        this.create();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnNhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapMoiActionPerformed
        // TODO add your handling code here:
        this.clear();
    }//GEN-LAST:event_btnNhapMoiActionPerformed

    private void tblBillDetaillsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBillDetaillsMouseClicked
        // TODO add your handling code here:
        int row = tblBillDetaills.getSelectedRow();
        if (row >= 0 && row < list.size()) {
            moveTo(row); // đổ dữ liệu dòng được chọn vào form
        }
        updateButtonStatus();
    }//GEN-LAST:event_tblBillDetaillsMouseClicked

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        this.delete();
    }//GEN-LAST:event_btnXoa1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhapMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBillDetaills;
    private javax.swing.JTextField txtMaGhe;
    private javax.swing.JTextField txtPhuPhi;
    // End of variables declaration//GEN-END:variables

    private final LoaiGheDAO dao = new LoaiGheDAOImpl();
    private List<LoaiGhe> list = new ArrayList<>();
    private int currentIndex = -1;

    @Override
    public void open() {
        fillToTable();
        clear();
        setEditable(true);
        updateButtonStatus();
    }

    private void updateButtonStatus() {
        boolean isSelected = tblBillDetaills.getSelectedRow() >= 0;
        btnThem.setEnabled(!isSelected); // Chỉ bật khi KHÔNG chọn dòng
        btnSua.setEnabled(isSelected);   // Bật khi có chọn dòng
        btnXoa1.setEnabled(isSelected);  // Bật khi có chọn dòng
    }

    @Override
    public void setForm(LoaiGhe entity) {
        txtMaGhe.setText(entity.getLoaiGhe());
        txtPhuPhi.setText(String.valueOf(entity.getPhuPhi()));
    }

    @Override
    public LoaiGhe getForm() {
        String ma = txtMaGhe.getText().trim();
        String phuPhiStr = txtPhuPhi.getText().trim();

        if (ma.isEmpty() || phuPhiStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin.");
            return null;
        }

        try {
            double phuPhi = Double.parseDouble(phuPhiStr);
            if (phuPhi < 0) {
                JOptionPane.showMessageDialog(this, "Phụ phí không được âm.");
                return null;
            }
            return new LoaiGhe(ma, phuPhi);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Phụ phí phải là số.");
            return null;
        }
    }

    @Override
    public void fillToTable() {
        list = dao.findAll();
        DefaultTableModel model = (DefaultTableModel) tblBillDetaills.getModel();
        model.setRowCount(0);
        for (LoaiGhe lg : list) {
            model.addRow(new Object[]{
                lg.getLoaiGhe(),
                lg.getPhuPhi()
            });
        }
        updateButtonStatus();
    }

    @Override
    public void edit() {
        moveTo(currentIndex);
    }

    @Override
    public void create() {
        LoaiGhe entity = getForm();
        if (entity != null) {
            if (dao.findById(entity.getLoaiGhe()) != null) {
                JOptionPane.showMessageDialog(this, "Mã ghế đã tồn tại!");
                return;
            }
            dao.create(entity);
            fillToTable();
            clear();
            JOptionPane.showMessageDialog(this, "Thêm mới thành công!");
        }
    }
@Override
public void update() {
    int row = tblBillDetaills.getSelectedRow();
    if (row < 0 || row >= list.size()) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn loại ghế cần cập nhật.");
        return;
    }

    LoaiGhe newEntity = getForm();
    if (newEntity == null) {
        return; // getForm đã báo lỗi rồi
    }

    // Lấy dữ liệu cũ trong DB
    LoaiGhe oldEntity = dao.findById(newEntity.getLoaiGhe());
    if (oldEntity == null) {
        JOptionPane.showMessageDialog(this, "Mã ghế không tồn tại để cập nhật!");
        return;
    }

    // ✅ So sánh xem có thay đổi gì không
    if (oldEntity.getPhuPhi() == newEntity.getPhuPhi()) {
        JOptionPane.showMessageDialog(this, "Không có thay đổi nào để cập nhật.");
        return;
    }

    // ✅ Nếu có thay đổi thì mới cập nhật
    try {
        dao.update(newEntity);
        fillToTable();
        clear();
        updateButtonStatus();
        JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi cập nhật: ");
        e.printStackTrace();
    }
}

    @Override
    public void delete() {
        int row = tblBillDetaills.getSelectedRow();
        if (row >= 0 && row < list.size()) {
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa loại ghế này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                String ma = (String) tblBillDetaills.getValueAt(row, 0);
                dao.deleteById(ma);
                fillToTable();
                clear();
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn loại ghế cần xóa.");
        }
    }

    @Override
    public void clear() {
        txtMaGhe.setText("");
        txtPhuPhi.setText("");
        tblBillDetaills.clearSelection();
        currentIndex = -1;
        updateButtonStatus();
    }

    @Override
    public void setEditable(boolean editable) {
        txtMaGhe.setEditable(editable);
    }

    @Override
    public void moveFirst() {
        moveTo(0);
    }

    @Override
    public void movePrevious() {
        if (currentIndex > 0) {
            moveTo(currentIndex - 1);
        }
    }

    @Override
    public void moveNext() {
        if (currentIndex < list.size() - 1) {
            moveTo(currentIndex + 1);
        }
    }

    @Override
    public void moveLast() {
        moveTo(list.size() - 1);
    }

    @Override
    public void moveTo(int rowIndex) {
        if (rowIndex >= 0 && rowIndex < list.size()) {
            currentIndex = rowIndex;
            setForm(list.get(currentIndex));
        }
    }

    @Override
    public void selectTimeRange() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
