/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package poly.cinema.ui.manager;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import poly.cinema.dao.QuanLyGheDao;
import poly.cinema.dao.impl.QuanLyGheDaoImpl;
import poly.cinema.dao.impl.QuanLyPhongChieuDaoImpl;
import poly.cinema.entity.PhongChieu;
import poly.cinema.entity.QuanLyGhe;
import poly.cinema.util.XDialog;

/**
 *
 * @author Admin
 */
public class QuanLyGheJpanel extends javax.swing.JPanel implements QuanLyGheController {

    /**
     * Creates new form QuanLyGheJpanel
     */
    public QuanLyGheJpanel() {
        initComponents();
        open();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cboPhongChieu = new javax.swing.JComboBox<>();
        cboLoaiGhe = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtSoHang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoCot = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtSoGhe = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGhe = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1110, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ GHẾ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 6, 291, 88));

        jPanel3.setBackground(new java.awt.Color(212, 212, 212));
        jPanel3.setPreferredSize(new java.awt.Dimension(111, 111));

        jLabel7.setText("Mã phòng chiếu");

        cboPhongChieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPhongChieuActionPerformed(evt);
            }
        });

        cboLoaiGhe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thường", "Vip", " " }));
        cboLoaiGhe.setToolTipText("");
        cboLoaiGhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiGheActionPerformed(evt);
            }
        });

        jLabel3.setText("Số hàng");

        txtSoHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoHangActionPerformed(evt);
            }
        });

        jLabel4.setText("Số cột");

        txtSoCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoCotActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 204));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("Tạo ghế");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel9.setText("Loại ghế");

        jCheckBox1.setText("Tạo Ghế Nhanh");

        jLabel5.setText("Số ghế");

        txtSoGhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoGheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoHang, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoCot, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLoaiGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(71, 71, 71))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboPhongChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSoGhe, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                    .addComponent(txtSoCot))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(25, 25, 25)
                                        .addComponent(txtSoHang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboLoaiGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboPhongChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 130, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1))))
                .addGap(52, 52, 52))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 1030, 220));

        tblGhe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã ghế", "Số ghế", "Số hàng", "Số cột", "Loại ghế", "Mã phòng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGhe.setRowHeight(25);
        tblGhe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGheMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGhe);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 1030, 240));

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, -1, 30));

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 620, -1, 30));

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 620, -1, 30));

        btnMoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMoi.setText("Nhập Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        add(btnMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 620, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        create();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        clear();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void txtSoGheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoGheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoGheActionPerformed

    private void txtSoHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoHangActionPerformed

    private void txtSoCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoCotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoCotActionPerformed

    private void tblGheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGheMouseClicked
        int row = tblGhe.getSelectedRow();
        if (row >= 0) {
            QuanLyGhe ghe = items.get(row);
            setForm(ghe);
            updateButtonState();
        }
    }//GEN-LAST:event_tblGheMouseClicked

    private void cboLoaiGheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiGheActionPerformed

    }//GEN-LAST:event_cboLoaiGheActionPerformed

    private void cboPhongChieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPhongChieuActionPerformed
        cboPhongChieu.addItemListener(e -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                fillToTable();
            }
        });
    }//GEN-LAST:event_cboPhongChieuActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        taoSoDoGhe();
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboLoaiGhe;
    private javax.swing.JComboBox<String> cboPhongChieu;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGhe;
    private javax.swing.JTextField txtSoCot;
    private javax.swing.JTextField txtSoGhe;
    private javax.swing.JTextField txtSoHang;
    // End of variables declaration//GEN-END:variables

    QuanLyGheDao dao = new QuanLyGheDaoImpl();
    List<QuanLyGhe> items = new ArrayList<>();
    
    private void updateButtonState() {
    boolean isRowSelected = tblGhe.getSelectedRow() >= 0;

    btnThem.setEnabled(!isRowSelected);
    btnSua.setEnabled(isRowSelected);
    btnXoa.setEnabled(isRowSelected);
}

    private void taoSoDoGhe() {
    String maPhong = (String) cboPhongChieu.getSelectedItem();
    int soHang, soCot;
    try {
        soHang = Integer.parseInt(txtSoHang.getText().trim());
        soCot = Integer.parseInt(txtSoCot.getText().trim());
    } catch (NumberFormatException e) {
        XDialog.alert("Số hàng và cột phải là số nguyên!");
        return;
    }

    if (soHang <= 0 || soCot <= 0 || soHang > 26) {
        XDialog.alert("Số hàng phải > 0 và ≤ 26, số cột > 0");
        return;
    }

    // Lấy thông tin phòng chiếu từ DB
    PhongChieu phong = new QuanLyPhongChieuDaoImpl().findByMaPhong(maPhong);
    if (phong == null) {
        XDialog.alert("Không tìm thấy thông tin phòng chiếu: " + maPhong);
        return;
    }

    // Kiểm tra vượt cấu hình của phòng
    if (soHang > phong.getSoHang() || soCot > phong.getSoCot()) {
        XDialog.alert("Phòng chiếu không đủ số ghế đó!\n" +
                      "Cấu hình tối đa: " + phong.getSoHang() + " hàng, " + phong.getSoCot() + " cột.");
        return;
    }

    int gheDaTao = 0;
    for (int i = 0; i < soHang; i++) {
        char hang = (char) ('A' + i);
        String loaiGhe = (i < 3) ? "Thường" : "VIP";

        for (int cot = 1; cot <= soCot; cot++) {
            String soGhe = hang + String.valueOf(cot);
            if (dao.findBySoGheAndPhong(soGhe, maPhong) != null) {
                continue;
            }

            QuanLyGhe ghe = QuanLyGhe.builder()
                    .maPhong(maPhong)
                    .soGhe(soGhe)
                    .hang(String.valueOf(hang))
                    .cot(cot)
                    .loaiGhe(loaiGhe)
                    .build();

            dao.create(ghe);
            gheDaTao++;
        }
    }

    XDialog.alert("Đã tạo " + gheDaTao + " ghế cho phòng " + maPhong);
    fillToTable();
}



    @Override
    public void open() {
        addListeners();
        fillComboBoxPhong();
        fillComboBoxLoaiGhe(); // ✅ Thêm dòng này
        fillToTable();
        clear();
    }

    private void addListeners() {
        cboPhongChieu.addItemListener(e -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                fillToTable();
            }
        });
    }

    private void fillComboBoxLoaiGhe() {
        cboLoaiGhe.removeAllItems();
        cboLoaiGhe.addItem("Thường");
        cboLoaiGhe.addItem("VIP");
    }

    private void fillComboBoxPhong() {
        cboPhongChieu.removeAllItems();
        List<String> dsPhong = dao.getAllMaPhong();
        for (String maPhong : dsPhong) {
            cboPhongChieu.addItem(maPhong);
        }
    }

    @Override
    public QuanLyGhe getForm() {
        QuanLyGhe ghe = new QuanLyGhe();
        String hang = txtSoHang.getText().trim();
        String cotText = txtSoCot.getText().trim();

        ghe.setHang(hang);
        int cot;
        try {
            cot = Integer.parseInt(cotText);
            ghe.setCot(cot);
        } catch (NumberFormatException e) {
            XDialog.alert("Cột phải là số nguyên!");
            return null;
        }

        String soGhe = txtSoGhe.getText().trim();
        if (soGhe.isEmpty()) {
            soGhe = hang + cot;
        }
        ghe.setSoGhe(soGhe);

        ghe.setLoaiGhe((String) cboLoaiGhe.getSelectedItem());
        ghe.setMaPhong((String) cboPhongChieu.getSelectedItem());
        return ghe;
    }

    @Override
    public void setForm(QuanLyGhe ghe) {
        txtSoGhe.setText(ghe.getSoGhe());
        txtSoHang.setText(ghe.getHang());
        txtSoCot.setText(String.valueOf(ghe.getCot()));
        cboLoaiGhe.setSelectedItem(ghe.getLoaiGhe());
        cboPhongChieu.setSelectedItem(ghe.getMaPhong());
    }

    @Override
    public void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tblGhe.getModel();
        model.setRowCount(0);
        String maPhong = (String) cboPhongChieu.getSelectedItem();
        if (maPhong != null) {
            items = dao.findByPhong(maPhong);
            for (QuanLyGhe ghe : items) {
                model.addRow(new Object[]{
                    ghe.getMaGhe(),
                    ghe.getSoGhe(),
                    ghe.getHang(),
                    ghe.getCot(),
                    ghe.getLoaiGhe(),
                    ghe.getMaPhong(),
                    false
                });
            }
        }
        updateButtonState();
    }

    @Override
    public void create() {
        QuanLyGhe ghe = getForm();
        if (ghe == null) {
            return;
        }

        QuanLyGhe existed = dao.findBySoGheAndPhong(ghe.getSoGhe(), ghe.getMaPhong());
        if (existed != null) {
            XDialog.alert("Ghế " + ghe.getSoGhe() + " đã tồn tại trong phòng " + ghe.getMaPhong() + "!");
            return;
        }

        dao.create(ghe);
        fillToTable();
        clear();
        XDialog.alert("Thêm ghế thành công!");
    }

    @Override
    public void update() {
        int row = tblGhe.getSelectedRow();
        if (row < 0) {
            XDialog.alert("Vui lòng chọn ghế để cập nhật!");
            return;
        }

        QuanLyGhe ghe = getForm();
        if (ghe == null) {
            return;
        }

        ghe.setMaGhe((Integer) tblGhe.getValueAt(row, 0));
        dao.update(ghe);
        fillToTable();
        XDialog.alert("Cập nhật ghế thành công!");
    }

    @Override
    public void delete() {
        int row = tblGhe.getSelectedRow();
        if (row < 0) {
            XDialog.alert("Vui lòng chọn ghế để xóa!");
            return;
        }
        int maGhe = (Integer) tblGhe.getValueAt(row, 0);
        dao.deleteById(maGhe);
        fillToTable();
        clear();
        XDialog.alert("Xóa ghế thành công!");
    }

    @Override
    public void clear() {
        txtSoGhe.setText("");
        txtSoHang.setText("");
        txtSoCot.setText("");

        if (cboLoaiGhe.getItemCount() > 0) {
            cboLoaiGhe.setSelectedIndex(0);
        }
        if (cboPhongChieu.getItemCount() > 0) {
            cboPhongChieu.setSelectedIndex(0);
        }

        tblGhe.clearSelection();
        
        updateButtonState();
    }

    @Override
    public void edit() {
        int row = tblGhe.getSelectedRow();
        if (row >= 0) {
            QuanLyGhe ghe = items.get(row);
            setForm(ghe);
            tblGhe.setRowSelectionInterval(row, row);
        } else {
            XDialog.alert("Vui lòng chọn ghế để chỉnh sửa.");
        }
    }

    @Override
    public void setEditable(boolean editable) {
        txtSoGhe.setEditable(editable);
        txtSoHang.setEditable(editable);
        txtSoCot.setEditable(editable);
        cboLoaiGhe.setEnabled(editable);
        cboPhongChieu.setEnabled(editable);
    }

    @Override
    public void moveFirst() {
        if (!items.isEmpty()) {
            moveTo(0);
        }
    }

    @Override
    public void movePrevious() {
        int row = tblGhe.getSelectedRow();
        if (row > 0) {
            moveTo(row - 1);
        }
    }

    @Override
    public void moveNext() {
        int row = tblGhe.getSelectedRow();
        if (row < items.size() - 1) {
            moveTo(row + 1);
        }
    }

    @Override
    public void moveLast() {
        if (!items.isEmpty()) {
            moveTo(items.size() - 1);
        }
    }

    @Override
    public void moveTo(int rowIndex) {
        if (rowIndex >= 0 && rowIndex < items.size()) {
            QuanLyGhe ghe = items.get(rowIndex);
            setForm(ghe);
            tblGhe.setRowSelectionInterval(rowIndex, rowIndex);
        }
    }

    @Override
    public void selectTimeRange() {
        // Không áp dụng
    }

}
