/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package poly.cinema.ui.manager;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.net.URL;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JViewport;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import poly.cinema.dao.QuanLyPhimDao;
import poly.cinema.dao.QuanLySuatChieuDao;
import poly.cinema.dao.impl.QuanLyPhimDaoImpl;
import poly.cinema.dao.impl.QuanLySuatChieuDaoImpl;
import poly.cinema.entity.Phim;
import poly.cinema.entity.SuatChieu;

/**
 *
 * @author Admin
 */
public class XemLichChieu extends javax.swing.JPanel {
// ==== CARD CONSTANTS ====

    /**
     * Creates new form XemLichChieu
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlChiTiet = new javax.swing.JPanel();
        scpDanhSachPhim = new javax.swing.JScrollPane();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Xem Lịch Chiếu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 14, 343, 70));

        pnlChiTiet.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlChiTiet.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        javax.swing.GroupLayout pnlChiTietLayout = new javax.swing.GroupLayout(pnlChiTiet);
        pnlChiTiet.setLayout(pnlChiTietLayout);
        pnlChiTietLayout.setHorizontalGroup(
            pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        pnlChiTietLayout.setVerticalGroup(
            pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        jPanel1.add(pnlChiTiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 110, 320, -1));
        jPanel1.add(scpDanhSachPhim, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 785, 606));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlChiTiet;
    private javax.swing.JScrollPane scpDanhSachPhim;
    // End of variables declaration//GEN-END:variables
private static final int CARD_W = 150;
    private static final int CARD_H = 240;
    private static final int POSTER_H = 190;

// ==== STYLE ====
    private static final Color CARD_BORDER = Color.GRAY;
    private static final Color CARD_BG = Color.WHITE;
    private static final Color CARD_BG_HOVER = new Color(245, 245, 245);
    private static final Font TITLE_FONT = new Font("Arial", Font.BOLD, 14);
    private static final Font SCHEDULE_FONT = new Font("Arial", Font.PLAIN, 14);

// ==== SCROLL WRAPPER ====
    private JPanel pnlGrid; // Panel mới để đặt vào ScrollPane

    public XemLichChieu() {
        initComponents();

        // Tạo panel mới thay cho pnlDanhSachPhim
        pnlGrid = new JPanel();
        pnlGrid.setBackground(new Color(0xE0E3EB));

        // Set layout mặc định (GridLayout sẽ set lại trong open)
        pnlGrid.setLayout(new GridLayout(0, 5, 5, 5));

        // Gắn panel này vào ScrollPane
        scpDanhSachPhim.setViewportView(pnlGrid);
        scpDanhSachPhim.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scpDanhSachPhim.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scpDanhSachPhim.getVerticalScrollBar().setUnitIncrement(16);

        pnlChiTiet.setLayout(new BoxLayout(pnlChiTiet, BoxLayout.Y_AXIS));
        pnlChiTiet.setBackground(Color.WHITE);

        SwingUtilities.invokeLater(this::open);
    }

    public void open() {
        pnlGrid.removeAll();

        QuanLyPhimDao phimDao = new QuanLyPhimDaoImpl();
        List<Phim> dsPhim = phimDao.findPhimChieuHomNay();

        int cols = 5;
        int rows = (int) Math.ceil(dsPhim.size() / (double) cols);
        pnlGrid.setLayout(new GridLayout(rows, cols, 5, 5));

        for (Phim phim : dsPhim) {
            pnlGrid.add(taoCardPhim(phim));
        }

        pnlGrid.revalidate();
        pnlGrid.repaint();
    }

    private JPanel taoCardPhim(Phim phim) {
        JPanel pnlPhim = new JPanel(new BorderLayout());
        pnlPhim.setPreferredSize(new Dimension(CARD_W, CARD_H));
        pnlPhim.setBorder(BorderFactory.createLineBorder(CARD_BORDER));
        pnlPhim.setBackground(CARD_BG);
        pnlPhim.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        JLabel lblHinh = new JLabel("", JLabel.CENTER);
        lblHinh.setPreferredSize(new Dimension(CARD_W, POSTER_H));
        ImageIcon icon = loadPosterIcon(phim.getHinhAnh(), CARD_W, POSTER_H);
        if (icon != null) {
            lblHinh.setIcon(icon);
        } else {
            lblHinh.setText("<html><center>Không có<br>ảnh</center></html>");
        }

        JLabel lblTenPhim = new JLabel(
                "<html><div style='text-align:center;white-space:normal;'>"
                + escapeHtml(phim.getTenPhim()) + "</div></html>", JLabel.CENTER
        );

        lblTenPhim.setFont(TITLE_FONT);
        lblTenPhim.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));

        pnlPhim.add(lblHinh, BorderLayout.CENTER);
        pnlPhim.add(lblTenPhim, BorderLayout.SOUTH);

        pnlPhim.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                hienThiLichChieu(phim);
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                pnlPhim.setBackground(CARD_BG_HOVER);
                pnlPhim.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                pnlPhim.setBackground(CARD_BG);
                pnlPhim.setBorder(BorderFactory.createLineBorder(CARD_BORDER));
            }
        });

        return pnlPhim;
    }

    private ImageIcon loadPosterIcon(String fileName, int targetW, int targetH) {
        if (fileName == null || fileName.isBlank()) {
            return null;
        }

        File f = new File("images", fileName);
        if (f.exists()) {
            return scaleIcon(new ImageIcon(f.getAbsolutePath()), targetW, targetH);
        }

        URL url = getClass().getResource("/images/" + fileName);
        if (url != null) {
            return scaleIcon(new ImageIcon(url), targetW, targetH);
        }
        return null;
    }

    private ImageIcon scaleIcon(ImageIcon raw, int targetW, int targetH) {
        if (raw.getIconWidth() <= 0 || raw.getIconHeight() <= 0) {
            return null;
        }
        double scale = Math.min((double) targetW / raw.getIconWidth(), (double) targetH / raw.getIconHeight());
        int w = (int) (raw.getIconWidth() * scale);
        int h = (int) (raw.getIconHeight() * scale);
        Image scaled = raw.getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
        return new ImageIcon(scaled);
    }

    // ==== helper: escape + center HTML ====
private String escapeHtmlHtmlCenter(String s, int maxWidthPx) {
    return "<html><div style='text-align:center;width:" + maxWidthPx + "px;word-wrap:break-word;'>"
            + escapeHtml(s == null ? "" : s) + "</div></html>";
}

// ==== helper: ép component chiếm full chiều ngang pnlChiTiet ====
private void makeFullWidth(JComponent c) {
    c.setAlignmentX(Component.CENTER_ALIGNMENT); // giữ toàn bộ block ở trung tâm dọc theo Y_AXIS
    Dimension pref = c.getPreferredSize();
    // rộng vô hạn để BoxLayout choãn hết; cao theo pref
    c.setMaximumSize(new Dimension(Integer.MAX_VALUE, pref.height));
}

// ==== hiển thị chi tiết lịch chiếu ====
private void hienThiLichChieu(Phim phim) {
    pnlChiTiet.removeAll();
    pnlChiTiet.setLayout(new BoxLayout(pnlChiTiet, BoxLayout.Y_AXIS));
    pnlChiTiet.setBackground(Color.WHITE);

    String tenPhim = phim.getTenPhim() == null ? "" : phim.getTenPhim();

    // --- Title ---
    // CARD_W = 150, trừ padding → lấy khoảng 140
JLabel lblTitle = new JLabel(escapeHtmlHtmlCenter(tenPhim, 140), JLabel.CENTER);
lblTitle.setFont(new Font("Arial", Font.BOLD, 18));
lblTitle.setBorder(BorderFactory.createEmptyBorder(10, 10, 5, 10));
lblTitle.setToolTipText(tenPhim);
makeFullWidth(lblTitle);
pnlChiTiet.add(lblTitle);


    // --- Separator ---
    pnlChiTiet.add(Box.createVerticalStrut(4));
    Component sep = taoFullWidthSeparator();
    pnlChiTiet.add(sep);
    pnlChiTiet.add(Box.createVerticalStrut(8));

    // --- Ngày ---
    LocalDate homNay = LocalDate.now();
    JLabel lblNgay = new JLabel("Suất chiếu hôm nay: " + homNay, JLabel.CENTER);
    lblNgay.setFont(new Font("Arial", Font.ITALIC, 13));
    lblNgay.setForeground(Color.DARK_GRAY);
    lblNgay.setBorder(BorderFactory.createEmptyBorder(0, 10, 10, 10));
    makeFullWidth(lblNgay);
    pnlChiTiet.add(lblNgay);

    // --- Data ---
    QuanLySuatChieuDao dao = new QuanLySuatChieuDaoImpl();
    java.sql.Date ngayHienTai = java.sql.Date.valueOf(homNay);
    List<SuatChieu> dsXuat = dao.findByNgayVaPhim(ngayHienTai, phim.getMaPhim());

    // // DEBUG (bật khi cần)
    // System.out.println("DEBUG >> phim=" + phim.getMaPhim() + ", homNay=" + homNay
    //         + ", soSuat=" + (dsXuat == null ? "null" : dsXuat.size()));

    if (dsXuat == null || dsXuat.isEmpty()) {
        JLabel lbl = new JLabel("Không có suất chiếu hôm nay.", JLabel.CENTER);
        lbl.setFont(new Font("Arial", Font.ITALIC, 14));
        lbl.setForeground(Color.GRAY);
        lbl.setBorder(BorderFactory.createEmptyBorder(20, 10, 20, 10));
        makeFullWidth(lbl);
        pnlChiTiet.add(lbl);
    } else {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm");

        JPanel listPanel = new JPanel();
        listPanel.setLayout(new BoxLayout(listPanel, BoxLayout.Y_AXIS));
        listPanel.setOpaque(false);
        listPanel.setAlignmentX(Component.CENTER_ALIGNMENT); // block giữa

        for (int i = 0; i < dsXuat.size(); i++) {
            Component row = taoDongSuatChieuCenter(dsXuat.get(i), dtf);
            listPanel.add(row);
            if (i < dsXuat.size() - 1) {
                listPanel.add(Box.createVerticalStrut(15)); // <<< KHOẢNG CÁCH 15PX
            }
        }

        makeFullWidth(listPanel);
        pnlChiTiet.add(listPanel);
    }

    pnlChiTiet.add(Box.createVerticalStrut(20));
    pnlChiTiet.revalidate();
    pnlChiTiet.repaint();
}

// ==== tạo 1 dòng suất chiếu, căn giữa ====
private Component taoDongSuatChieuCenter(SuatChieu x, DateTimeFormatter dtf) {
    LocalTime gio = x.getGioChieu();
    String gioText = (gio != null ? gio.format(dtf) : "??:??");
    String phong = (x.getMaPhong() != null ? x.getMaPhong() : "?");
    String text = gioText + "  •  Phòng " + phong;

    JLabel lblShow = new JLabel(text, JLabel.CENTER);
    lblShow.setFont(SCHEDULE_FONT);
    lblShow.setOpaque(true);
    lblShow.setBackground(Color.WHITE);
    lblShow.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(Color.LIGHT_GRAY),
            BorderFactory.createEmptyBorder(5, 25, 5, 25) // padding trong nút; tăng chút cho dễ click
    ));

    lblShow.addMouseListener(new MouseAdapter() {
        @Override public void mouseEntered(MouseEvent e) { lblShow.setBackground(CARD_BG_HOVER); }
        @Override public void mouseExited (MouseEvent e) { lblShow.setBackground(Color.WHITE); }
        // @Override public void mouseClicked(MouseEvent e) { openBooking(x); } // nếu cần
    });

    JPanel row = new JPanel(new BorderLayout());
    row.setOpaque(false);
    row.setAlignmentX(Component.CENTER_ALIGNMENT); // hàng giữa
    row.add(lblShow, BorderLayout.CENTER);

    // Không ép max width vô hạn ở đây; để row rộng = lblShow → nhìn đúng “nút giữa”
    // Nếu muốn hàng kéo full ngang: bỏ comment dưới
    // row.setMaximumSize(new Dimension(Integer.MAX_VALUE, row.getPreferredSize().height));

    return row;
}




    private String escapeHtml(String s) {
        if (s == null) {
            return "";
        }
        return s.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;");
    }

    private Component taoFullWidthSeparator() {
        JPanel wrap = new JPanel(new BorderLayout());
        wrap.setOpaque(false);
        JSeparator sep = new JSeparator(SwingConstants.HORIZONTAL);
        wrap.add(sep, BorderLayout.CENTER);
        wrap.setMaximumSize(new Dimension(Integer.MAX_VALUE, 1));
        wrap.setAlignmentX(Component.LEFT_ALIGNMENT);
        return wrap;
    }

}
