/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package poly.cinema.ui;

import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import poly.cinema.dao.NguoiDungDAO;
import poly.cinema.dao.impl.NguoiDungDAOImpl;
import poly.cinema.util.CaptchaGenerator;
import poly.cinema.util.XAuth;


/**
 *
 * @author Bao Nhien
 */
public class DoiMatKhau extends javax.swing.JPanel implements DoiMatKhauController {

    private String currentCaptcha;

    /**
     * Creates new form DoiMatKhau
     */
    public DoiMatKhau() {
        initComponents();
        loadCaptcha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCaptcha = new javax.swing.JTextField();
        lblLoiCaptcha = new javax.swing.JLabel();
        lblLoiConfirm = new javax.swing.JLabel();
        txtConfirm = new javax.swing.JTextField();
        lblLoiNewPass = new javax.swing.JLabel();
        txtNewpass = new javax.swing.JTextField();
        lblLoiPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblLoiUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblCaptchaImage = new javax.swing.JLabel();
        btnReloadCaptcha = new javax.swing.JButton();
        bntExit = new javax.swing.JButton();
        bntSave = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1110, 720));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(1110, 720));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đổi mật khẩu");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/anhdoimatkhau.png"))); // NOI18N
        jLabel9.setText("jLabel9");

        jPanel1.setBackground(new java.awt.Color(212, 212, 212));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Nhập mã captcha");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Xác nhận lại mật khẩu mới");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Mật khẩu mới");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Mật khẩu hiện tại");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tên đăng nhập");

        txtCaptcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaptchaActionPerformed(evt);
            }
        });

        lblLoiCaptcha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLoiCaptcha.setForeground(new java.awt.Color(255, 51, 102));
        lblLoiCaptcha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblLoiConfirm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLoiConfirm.setForeground(new java.awt.Color(255, 51, 102));
        lblLoiConfirm.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblLoiNewPass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLoiNewPass.setForeground(new java.awt.Color(255, 51, 102));
        lblLoiNewPass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtNewpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewpassActionPerformed(evt);
            }
        });

        lblLoiPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLoiPassword.setForeground(new java.awt.Color(255, 51, 102));
        lblLoiPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblLoiUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLoiUsername.setForeground(new java.awt.Color(255, 51, 102));
        lblLoiUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btnReloadCaptcha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReloadCaptcha.setText("Làm mới");
        btnReloadCaptcha.setContentAreaFilled(false);
        btnReloadCaptcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadCaptchaActionPerformed(evt);
            }
        });

        bntExit.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        bntExit.setText("HỦY BỎ");
        bntExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExitActionPerformed(evt);
            }
        });

        bntSave.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        bntSave.setText("LƯU");
        bntSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntSave, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(bntExit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtConfirm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                                .addComponent(txtNewpass, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblLoiUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLoiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLoiNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLoiConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLoiCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCaptchaImage, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnReloadCaptcha)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLoiUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(3, 3, 3)
                .addComponent(lblLoiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewpass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoiNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoiConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoiCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReloadCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCaptchaImage, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntExit)
                    .addComponent(bntSave))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1145, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bntSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSaveActionPerformed
        this.save();
    }//GEN-LAST:event_bntSaveActionPerformed

    private void bntExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExitActionPerformed
        txtUsername.setText("");
        txtPassword.setText("");
        txtNewpass.setText("");
        txtConfirm.setText("");
        txtCaptcha.setText("");
        loadCaptcha();
    }//GEN-LAST:event_bntExitActionPerformed

    private void btnReloadCaptchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadCaptchaActionPerformed
        loadCaptcha();

    }//GEN-LAST:event_btnReloadCaptchaActionPerformed

    private void txtNewpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewpassActionPerformed

    private void txtCaptchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaptchaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaptchaActionPerformed

    NguoiDungDAO dao = new NguoiDungDAOImpl();

    @Override
    public void save() {
        String email = txtUsername.getText().trim();
        String matKhau = txtPassword.getText();
        String newpass = txtNewpass.getText();
        String confirm = txtConfirm.getText();
        String userCaptcha = txtCaptcha.getText().trim();

        clearErrorLabels();

        boolean isValid = true;

        if (!email.equals(XAuth.user.getEmail())) {
            lblLoiUsername.setText("Sai tên đăng nhập");
            isValid = false;
        }

        if (!matKhau.equals(XAuth.user.getMatKhau())) {
            lblLoiPassword.setText("Sai mật khẩu");
            isValid = false;
        }

        if (newpass.length() < 8) {
            lblLoiNewPass.setText("Mật khẩu phải từ 8 ký tự trở lên");
            isValid = false;
        } else if (!newpass.matches(".*[A-Z].*")) {
            lblLoiNewPass.setText("Phải có ít nhất 1 chữ in hoa");
            isValid = false;
        } else if (!newpass.matches(".*[a-z].*")) {
            lblLoiNewPass.setText("Phải có ít nhất 1 chữ thường");
            isValid = false;
        } else if (!newpass.matches(".*\\d.*")) {
            lblLoiNewPass.setText("Phải có ít nhất 1 chữ số");
            isValid = false;
        } else if (!newpass.matches(".*[!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>\\/?].*")) {
            lblLoiNewPass.setText("Phải có ít nhất 1 ký tự đặc biệt");
            isValid = false;
        } else if (newpass.contains(" ")) {
            lblLoiNewPass.setText("Không được chứa khoảng trắng");
            isValid = false;
        } else if (newpass.toLowerCase().contains(email.toLowerCase())) {
            lblLoiNewPass.setText("Không được chứa tên đăng nhập");
            isValid = false;
        }

        if (!newpass.equals(confirm)) {
            lblLoiConfirm.setText("Mật khẩu không khớp");
            isValid = false;
        }

        if (!userCaptcha.equals(currentCaptcha)) {
            lblLoiCaptcha.setText("Mã captcha không đúng!");
            isValid = false;
            loadCaptcha();
        }

        if (isValid) {
            XAuth.user.setMatKhau(newpass);
            dao.update(XAuth.user);
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công!");
            loadCaptcha();
        }
    }

    private void clearErrorLabels() {
        lblLoiUsername.setText("");
        lblLoiPassword.setText("");
        lblLoiNewPass.setText("");
        lblLoiConfirm.setText("");
        lblLoiCaptcha.setText("");
    }

    private void loadCaptcha() {
        currentCaptcha = CaptchaGenerator.generateText(5);
        BufferedImage image = CaptchaGenerator.generateImage(currentCaptcha);
        lblCaptchaImage.setIcon(new ImageIcon(image));
    }

    @Override
    public void open() {
        this.setVisible(true);            // Hiển thị form
        loadCaptcha();                    // Tải Captcha lần đầu
    }

    @Override
    public void close() {
        this.setVisible(false); // Ẩn form
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntExit;
    private javax.swing.JButton bntSave;
    private javax.swing.JButton btnReloadCaptcha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCaptchaImage;
    private javax.swing.JLabel lblLoiCaptcha;
    private javax.swing.JLabel lblLoiConfirm;
    private javax.swing.JLabel lblLoiNewPass;
    private javax.swing.JLabel lblLoiPassword;
    private javax.swing.JLabel lblLoiUsername;
    private javax.swing.JTextField txtCaptcha;
    private javax.swing.JTextField txtConfirm;
    private javax.swing.JTextField txtNewpass;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    

}