package poly.cinema.ui;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import poly.cinema.util.XAuth;
import poly.cinema.util.XDialog;
import poly.cinema.util.XIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class FCinema_Frame extends javax.swing.JFrame implements FCinema_Controller {

    private CardLayout cardLayout = new CardLayout();
    /**
     * Creates new form FCinema_Frame
     */
    public FCinema_Frame() {
        initComponents();
        init();
        setLocationRelativeTo(null);
        pnlBanHang = new BanHang(pnlMainContent);
        pnlMainContent.removeAll();
        pnlMainContent.setLayout(new CardLayout());

        pnlQuanLyPhim = new poly.cinema.ui.manager.QuanLyPhim();
        pnlQuanLyPhongChieu = new poly.cinema.ui.manager.QuanLiPhongChieu();
        pnlDoiMatKhau = new poly.cinema.ui.DoiMatKhau();
        pnlQuanLyNhanVien = new poly.cinema.ui.manager.QuanLiNhanVien();
        pnlThongKeDoanhThu = new poly.cinema.ui.manager.ThongKePanel();
        pnlQuanLyHoaDon = new poly.cinema.ui.manager.QuanLyHoaDonJpanel();
        pnlXemLichChieu = new poly.cinema.ui.manager.XemLichChieu();
        pnlLichSuBanHang = new poly.cinema.ui.manager.LichSuBanHang();
        pnlQuanLyGhe = new poly.cinema.ui.manager.QuanLyGheJpanel();
        pnlQuanLySanPham = new poly.cinema.ui.manager.QuanLySanPham();
        pnlQuanLySuatChieu = new poly.cinema.ui.manager.QuanLyXuatChieu();
        pnlLoaighe = new poly.cinema.ui.manager.LoaiGheJpanel();
        pnlLoaiPhim = new poly.cinema.ui.manager.LoaiPhimPanel();
        
        pnlBanHang = new poly.cinema.ui.BanHang(pnlMainContent);
        pnlMainContent.add(pnlBanHang, "pnlBanHang");
        pnlChonPhim = new poly.cinema.ui.chonPhimJpanel(pnlMainContent);
        pnlMainContent.add(pnlChonPhim, "pnlChonPhim");
        pnlchonGhe = new poly.cinema.ui.chonGheJPanel(pnlMainContent);
        pnlMainContent.add(pnlchonGhe, "pnlchonGhe");
        pnlBanSanPham = new poly.cinema.ui.BanSanPham(pnlMainContent);
        pnlMainContent.add(pnlBanSanPham, "pnlBanSanPham");

        pnlMainContent.add(pnlLoaiPhim, "pnlLoaiPhim");
        pnlMainContent.add(pnlLoaighe, "pnlLoaighe");
        pnlMainContent.add(pnlQuanLyPhim, "pnlQuanLyPhim");
        pnlMainContent.add(pnlQuanLyPhongChieu, "pnlQuanLyPhongChieu");
        pnlMainContent.add(pnlQuanLyNhanVien, "pnlQuanLyNhanVien");
        pnlMainContent.add(pnlThongKeDoanhThu, "pnlThongKeDoanhThu");
        pnlMainContent.add(pnlDoiMatKhau, "pnlDoiMatKhau");
        pnlMainContent.add(pnlQuanLyHoaDon, "pnlQuanLyHoaDon");
        pnlMainContent.add(pnlXemLichChieu, "pnlXemLichChieu");
        pnlMainContent.add(pnlLichSuBanHang, "pnlLichSuBanHang");
        pnlMainContent.add(pnlQuanLyGhe, "pnlQuanLyGhe");
        pnlMainContent.add(pnlQuanLySanPham, "pnlQuanLySanPham");
        pnlMainContent.add(pnlQuanLySuatChieu, "pnlQuanLySuatChieu");

        pnlMainContent.add(pnlTrangchu, "pnlTrangchu");

        // Mặc định hiển thị Trang chủ
        CardLayout cl = (CardLayout) pnlMainContent.getLayout();
        cl.show(pnlMainContent, "pnlTrangchu");
        addHoverEffectToPanelLabels(pnlManager);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCenter = new javax.swing.JPanel();
        pnlManager = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblsuatchieu = new javax.swing.JLabel();
        lblLichSuBanHang = new javax.swing.JLabel();
        lblQLNHANVIEN = new javax.swing.JLabel();
        lblQLDoanhthu = new javax.swing.JLabel();
        lblQLHoaDon = new javax.swing.JLabel();
        lblBanVe = new javax.swing.JLabel();
        lblQLGhe = new javax.swing.JLabel();
        lblQLPhongChieu = new javax.swing.JLabel();
        lblQLSanPham = new javax.swing.JLabel();
        lblQLPhim = new javax.swing.JLabel();
        lblXemLichChieu = new javax.swing.JLabel();
        lbldoimk = new javax.swing.JLabel();
        lbldãnguat = new javax.swing.JLabel();
        lblQLPhongChieu1 = new javax.swing.JLabel();
        lblQLPhongChieu2 = new javax.swing.JLabel();
        pnlMainContent = new javax.swing.JPanel();
        pnlQuanLyPhongChieu = new javax.swing.JPanel();
        pnlQuanLyGhe = new javax.swing.JPanel();
        pnlBanVe = new javax.swing.JPanel();
        pnlQuanLyHoaDon = new javax.swing.JPanel();
        pnlQuanLyNhanVien = new javax.swing.JPanel();
        pnlTrangchu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlQuanLySanPham = new javax.swing.JPanel();
        pnlQuanLyPhim = new javax.swing.JPanel();
        pnlXemLichChieu = new javax.swing.JPanel();
        pnlThongKeDoanhThu = new javax.swing.JPanel();
        pnlLichSuBanHang = new javax.swing.JPanel();
        pnlQuanLySuatChieu = new javax.swing.JPanel();
        pnlDoiMatKhau = new javax.swing.JPanel();
        pnlLoaiPhim = new javax.swing.JPanel();
        pnlLoaiGhe = new javax.swing.JPanel();
        pnlBanHang = new javax.swing.JPanel();
        pnlchonGhe = new javax.swing.JPanel();
        pnlChonPhim = new javax.swing.JPanel();
        pnlBanSanPham = new javax.swing.JPanel();
        pnlLoaighe = new javax.swing.JPanel();
        lblFullname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlCenter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlManager.setBackground(new java.awt.Color(255, 255, 255));
        pnlManager.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/logonho.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        pnlManager.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 127, 111));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        pnlManager.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 240, 10));

        lblsuatchieu.setBackground(new java.awt.Color(255, 255, 255));
        lblsuatchieu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblsuatchieu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsuatchieu.setText("QUẢN LÝ SUẤT CHIẾU");
        lblsuatchieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsuatchieuMouseClicked(evt);
            }
        });
        pnlManager.add(lblsuatchieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 240, 37));

        lblLichSuBanHang.setBackground(new java.awt.Color(255, 255, 255));
        lblLichSuBanHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLichSuBanHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLichSuBanHang.setText("LỊCH SỬ BÁN HÀNG");
        lblLichSuBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLichSuBanHangMouseClicked(evt);
            }
        });
        pnlManager.add(lblLichSuBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 37));

        lblQLNHANVIEN.setBackground(new java.awt.Color(255, 255, 255));
        lblQLNHANVIEN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQLNHANVIEN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQLNHANVIEN.setText("QUẢN LÝ NHÂN VIÊN");
        lblQLNHANVIEN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLNHANVIENMouseClicked(evt);
            }
        });
        pnlManager.add(lblQLNHANVIEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 240, 37));

        lblQLDoanhthu.setBackground(new java.awt.Color(255, 255, 255));
        lblQLDoanhthu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQLDoanhthu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQLDoanhthu.setText("THỐNG KÊ DOANH THU");
        lblQLDoanhthu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLDoanhthuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQLDoanhthuMouseEntered(evt);
            }
        });
        pnlManager.add(lblQLDoanhthu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 240, 37));

        lblQLHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        lblQLHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQLHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQLHoaDon.setText("QUẢN LÝ HÓA ĐƠN");
        lblQLHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLHoaDonMouseClicked(evt);
            }
        });
        pnlManager.add(lblQLHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 240, 37));

        lblBanVe.setBackground(new java.awt.Color(255, 255, 255));
        lblBanVe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBanVe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanVe.setText("BÁN VÉ");
        lblBanVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanVeMouseClicked(evt);
            }
        });
        pnlManager.add(lblBanVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 240, 37));

        lblQLGhe.setBackground(new java.awt.Color(255, 255, 255));
        lblQLGhe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQLGhe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQLGhe.setText("QUẢN LÝ GHẾ");
        lblQLGhe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLGheMouseClicked(evt);
            }
        });
        pnlManager.add(lblQLGhe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 240, 37));

        lblQLPhongChieu.setBackground(new java.awt.Color(255, 255, 255));
        lblQLPhongChieu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQLPhongChieu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQLPhongChieu.setText("QUẢN LÝ PHÒNG CHIẾU");
        lblQLPhongChieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLPhongChieuMouseClicked(evt);
            }
        });
        pnlManager.add(lblQLPhongChieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 240, 37));

        lblQLSanPham.setBackground(new java.awt.Color(255, 255, 255));
        lblQLSanPham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQLSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQLSanPham.setText("QUẢN LÝ SẢN PHẨM ");
        lblQLSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLSanPhamMouseClicked(evt);
            }
        });
        pnlManager.add(lblQLSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 240, 37));

        lblQLPhim.setBackground(new java.awt.Color(255, 255, 255));
        lblQLPhim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQLPhim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQLPhim.setText("QUẢN LÝ PHIM");
        lblQLPhim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLPhimMouseClicked(evt);
            }
        });
        pnlManager.add(lblQLPhim, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 240, 37));

        lblXemLichChieu.setBackground(new java.awt.Color(255, 255, 255));
        lblXemLichChieu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblXemLichChieu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblXemLichChieu.setText("XEM LỊCH CHIẾU");
        lblXemLichChieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXemLichChieuMouseClicked(evt);
            }
        });
        pnlManager.add(lblXemLichChieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 240, 37));

        lbldoimk.setBackground(new java.awt.Color(255, 255, 255));
        lbldoimk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbldoimk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldoimk.setText("ĐỔI MẬT KHẨU");
        lbldoimk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldoimkMouseClicked(evt);
            }
        });
        pnlManager.add(lbldoimk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 240, 40));

        lbldãnguat.setBackground(new java.awt.Color(255, 255, 255));
        lbldãnguat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbldãnguat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldãnguat.setText("ĐĂNG XUẤT");
        lbldãnguat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldãnguatMouseClicked(evt);
            }
        });
        pnlManager.add(lbldãnguat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 240, 40));

        lblQLPhongChieu1.setBackground(new java.awt.Color(255, 255, 255));
        lblQLPhongChieu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQLPhongChieu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQLPhongChieu1.setText("QUẢN LÝ LOẠI GHẾ");
        lblQLPhongChieu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLPhongChieu1MouseClicked(evt);
            }
        });
        pnlManager.add(lblQLPhongChieu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 240, 37));

        lblQLPhongChieu2.setBackground(new java.awt.Color(255, 255, 255));
        lblQLPhongChieu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQLPhongChieu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQLPhongChieu2.setText("QUẢN LÝ LOẠI PHIM");
        lblQLPhongChieu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLPhongChieu2MouseClicked(evt);
            }
        });
        pnlManager.add(lblQLPhongChieu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 240, 37));

        pnlCenter.add(pnlManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 720));

        pnlMainContent.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pnlQuanLyPhongChieuLayout = new javax.swing.GroupLayout(pnlQuanLyPhongChieu);
        pnlQuanLyPhongChieu.setLayout(pnlQuanLyPhongChieuLayout);
        pnlQuanLyPhongChieuLayout.setHorizontalGroup(
            pnlQuanLyPhongChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        pnlQuanLyPhongChieuLayout.setVerticalGroup(
            pnlQuanLyPhongChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnlMainContent.add(pnlQuanLyPhongChieu, "card3");

        javax.swing.GroupLayout pnlQuanLyGheLayout = new javax.swing.GroupLayout(pnlQuanLyGhe);
        pnlQuanLyGhe.setLayout(pnlQuanLyGheLayout);
        pnlQuanLyGheLayout.setHorizontalGroup(
            pnlQuanLyGheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        pnlQuanLyGheLayout.setVerticalGroup(
            pnlQuanLyGheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnlMainContent.add(pnlQuanLyGhe, "card3");

        javax.swing.GroupLayout pnlBanVeLayout = new javax.swing.GroupLayout(pnlBanVe);
        pnlBanVe.setLayout(pnlBanVeLayout);
        pnlBanVeLayout.setHorizontalGroup(
            pnlBanVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        pnlBanVeLayout.setVerticalGroup(
            pnlBanVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnlMainContent.add(pnlBanVe, "card3");

        javax.swing.GroupLayout pnlQuanLyHoaDonLayout = new javax.swing.GroupLayout(pnlQuanLyHoaDon);
        pnlQuanLyHoaDon.setLayout(pnlQuanLyHoaDonLayout);
        pnlQuanLyHoaDonLayout.setHorizontalGroup(
            pnlQuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        pnlQuanLyHoaDonLayout.setVerticalGroup(
            pnlQuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnlMainContent.add(pnlQuanLyHoaDon, "card3");

        javax.swing.GroupLayout pnlQuanLyNhanVienLayout = new javax.swing.GroupLayout(pnlQuanLyNhanVien);
        pnlQuanLyNhanVien.setLayout(pnlQuanLyNhanVienLayout);
        pnlQuanLyNhanVienLayout.setHorizontalGroup(
            pnlQuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        pnlQuanLyNhanVienLayout.setVerticalGroup(
            pnlQuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnlMainContent.add(pnlQuanLyNhanVien, "card3");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/backgourd.png"))); // NOI18N

        javax.swing.GroupLayout pnlTrangchuLayout = new javax.swing.GroupLayout(pnlTrangchu);
        pnlTrangchu.setLayout(pnlTrangchuLayout);
        pnlTrangchuLayout.setHorizontalGroup(
            pnlTrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE)
        );
        pnlTrangchuLayout.setVerticalGroup(
            pnlTrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pnlMainContent.add(pnlTrangchu, "card2");

        javax.swing.GroupLayout pnlQuanLySanPhamLayout = new javax.swing.GroupLayout(pnlQuanLySanPham);
        pnlQuanLySanPham.setLayout(pnlQuanLySanPhamLayout);
        pnlQuanLySanPhamLayout.setHorizontalGroup(
            pnlQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        pnlQuanLySanPhamLayout.setVerticalGroup(
            pnlQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnlMainContent.add(pnlQuanLySanPham, "card3");

        javax.swing.GroupLayout pnlQuanLyPhimLayout = new javax.swing.GroupLayout(pnlQuanLyPhim);
        pnlQuanLyPhim.setLayout(pnlQuanLyPhimLayout);
        pnlQuanLyPhimLayout.setHorizontalGroup(
            pnlQuanLyPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        pnlQuanLyPhimLayout.setVerticalGroup(
            pnlQuanLyPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnlMainContent.add(pnlQuanLyPhim, "card3");

        javax.swing.GroupLayout pnlXemLichChieuLayout = new javax.swing.GroupLayout(pnlXemLichChieu);
        pnlXemLichChieu.setLayout(pnlXemLichChieuLayout);
        pnlXemLichChieuLayout.setHorizontalGroup(
            pnlXemLichChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        pnlXemLichChieuLayout.setVerticalGroup(
            pnlXemLichChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnlMainContent.add(pnlXemLichChieu, "card3");

        javax.swing.GroupLayout pnlThongKeDoanhThuLayout = new javax.swing.GroupLayout(pnlThongKeDoanhThu);
        pnlThongKeDoanhThu.setLayout(pnlThongKeDoanhThuLayout);
        pnlThongKeDoanhThuLayout.setHorizontalGroup(
            pnlThongKeDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        pnlThongKeDoanhThuLayout.setVerticalGroup(
            pnlThongKeDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnlMainContent.add(pnlThongKeDoanhThu, "card3");

        javax.swing.GroupLayout pnlLichSuBanHangLayout = new javax.swing.GroupLayout(pnlLichSuBanHang);
        pnlLichSuBanHang.setLayout(pnlLichSuBanHangLayout);
        pnlLichSuBanHangLayout.setHorizontalGroup(
            pnlLichSuBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        pnlLichSuBanHangLayout.setVerticalGroup(
            pnlLichSuBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnlMainContent.add(pnlLichSuBanHang, "card3");

        javax.swing.GroupLayout pnlQuanLySuatChieuLayout = new javax.swing.GroupLayout(pnlQuanLySuatChieu);
        pnlQuanLySuatChieu.setLayout(pnlQuanLySuatChieuLayout);
        pnlQuanLySuatChieuLayout.setHorizontalGroup(
            pnlQuanLySuatChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        pnlQuanLySuatChieuLayout.setVerticalGroup(
            pnlQuanLySuatChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnlMainContent.add(pnlQuanLySuatChieu, "card3");

        javax.swing.GroupLayout pnlDoiMatKhauLayout = new javax.swing.GroupLayout(pnlDoiMatKhau);
        pnlDoiMatKhau.setLayout(pnlDoiMatKhauLayout);
        pnlDoiMatKhauLayout.setHorizontalGroup(
            pnlDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        pnlDoiMatKhauLayout.setVerticalGroup(
            pnlDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnlMainContent.add(pnlDoiMatKhau, "card13");

        javax.swing.GroupLayout pnlLoaiPhimLayout = new javax.swing.GroupLayout(pnlLoaiPhim);
        pnlLoaiPhim.setLayout(pnlLoaiPhimLayout);
        pnlLoaiPhimLayout.setHorizontalGroup(
            pnlLoaiPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        pnlLoaiPhimLayout.setVerticalGroup(
            pnlLoaiPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnlMainContent.add(pnlLoaiPhim, "card15");

        javax.swing.GroupLayout pnlLoaiGheLayout = new javax.swing.GroupLayout(pnlLoaiGhe);
        pnlLoaiGhe.setLayout(pnlLoaiGheLayout);
        pnlLoaiGheLayout.setHorizontalGroup(
            pnlLoaiGheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        pnlLoaiGheLayout.setVerticalGroup(
            pnlLoaiGheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnlMainContent.add(pnlLoaiGhe, "card16");

        javax.swing.GroupLayout pnlBanHangLayout = new javax.swing.GroupLayout(pnlBanHang);
        pnlBanHang.setLayout(pnlBanHangLayout);
        pnlBanHangLayout.setHorizontalGroup(
            pnlBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        pnlBanHangLayout.setVerticalGroup(
            pnlBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnlMainContent.add(pnlBanHang, "card17");

        javax.swing.GroupLayout pnlchonGheLayout = new javax.swing.GroupLayout(pnlchonGhe);
        pnlchonGhe.setLayout(pnlchonGheLayout);
        pnlchonGheLayout.setHorizontalGroup(
            pnlchonGheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        pnlchonGheLayout.setVerticalGroup(
            pnlchonGheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnlMainContent.add(pnlchonGhe, "card18");

        javax.swing.GroupLayout pnlChonPhimLayout = new javax.swing.GroupLayout(pnlChonPhim);
        pnlChonPhim.setLayout(pnlChonPhimLayout);
        pnlChonPhimLayout.setHorizontalGroup(
            pnlChonPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        pnlChonPhimLayout.setVerticalGroup(
            pnlChonPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnlMainContent.add(pnlChonPhim, "card19");

        javax.swing.GroupLayout pnlBanSanPhamLayout = new javax.swing.GroupLayout(pnlBanSanPham);
        pnlBanSanPham.setLayout(pnlBanSanPhamLayout);
        pnlBanSanPhamLayout.setHorizontalGroup(
            pnlBanSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        pnlBanSanPhamLayout.setVerticalGroup(
            pnlBanSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnlMainContent.add(pnlBanSanPham, "card20");

        javax.swing.GroupLayout pnlLoaigheLayout = new javax.swing.GroupLayout(pnlLoaighe);
        pnlLoaighe.setLayout(pnlLoaigheLayout);
        pnlLoaigheLayout.setHorizontalGroup(
            pnlLoaigheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        pnlLoaigheLayout.setVerticalGroup(
            pnlLoaigheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnlMainContent.add(pnlLoaighe, "card21");

        pnlCenter.add(pnlMainContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 0, 1120, 720));

        lblFullname.setText("jLabel5");
        pnlCenter.add(lblFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 60, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblsuatchieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsuatchieuMouseClicked
        CardLayout cl = (CardLayout) pnlMainContent.getLayout();
        cl.show(pnlMainContent, "pnlQuanLySuatChieu");
        ((poly.cinema.ui.manager.QuanLyXuatChieu) pnlQuanLySuatChieu).open();
    }//GEN-LAST:event_lblsuatchieuMouseClicked

    private void lblLichSuBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLichSuBanHangMouseClicked
        CardLayout cl = (CardLayout) pnlMainContent.getLayout();
        cl.show(pnlMainContent, "pnlLichSuBanHang");
        ((poly.cinema.ui.manager.LichSuBanHang) pnlLichSuBanHang).open();
    }//GEN-LAST:event_lblLichSuBanHangMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        CardLayout cl = (CardLayout) pnlMainContent.getLayout();
        cl.show(pnlMainContent, "pnlTrangchu");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void lblQLNHANVIENMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLNHANVIENMouseClicked
        CardLayout cl = (CardLayout) pnlMainContent.getLayout();
        cl.show(pnlMainContent, "pnlQuanLyNhanVien");
        ((poly.cinema.ui.manager.QuanLiNhanVien) pnlQuanLyNhanVien).open();
    }//GEN-LAST:event_lblQLNHANVIENMouseClicked

    private void lblQLDoanhthuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLDoanhthuMouseClicked
        CardLayout cl = (CardLayout) pnlMainContent.getLayout();
        cl.show(pnlMainContent, "pnlThongKeDoanhThu");
        ((poly.cinema.ui.manager.ThongKePanel) pnlThongKeDoanhThu).open();
    }//GEN-LAST:event_lblQLDoanhthuMouseClicked

    private void lblQLHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLHoaDonMouseClicked
        CardLayout cl = (CardLayout) pnlMainContent.getLayout();
        cl.show(pnlMainContent, "pnlQuanLyHoaDon");
        ((poly.cinema.ui.manager.QuanLyHoaDonJpanel) pnlQuanLyHoaDon).open();
    }//GEN-LAST:event_lblQLHoaDonMouseClicked

    private void lblBanVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanVeMouseClicked
        CardLayout cl = (CardLayout) pnlMainContent.getLayout();
        cl.show(pnlMainContent, "pnlBanHang");
        ((poly.cinema.ui.BanHang) pnlBanHang).open();
    }//GEN-LAST:event_lblBanVeMouseClicked

    private void lblQLGheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLGheMouseClicked
        CardLayout cl = (CardLayout) pnlMainContent.getLayout();
        cl.show(pnlMainContent, "pnlQuanLyGhe");
        ((poly.cinema.ui.manager.QuanLyGheJpanel) pnlQuanLyGhe).open();
    }//GEN-LAST:event_lblQLGheMouseClicked

    private void lblQLDoanhthuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLDoanhthuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblQLDoanhthuMouseEntered

    private void lblQLPhongChieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLPhongChieuMouseClicked
        CardLayout cl = (CardLayout) pnlMainContent.getLayout();
        cl.show(pnlMainContent, "pnlQuanLyPhongChieu");
        ((poly.cinema.ui.manager.QuanLiPhongChieu) pnlQuanLyPhongChieu).open();
    }//GEN-LAST:event_lblQLPhongChieuMouseClicked

    private void lblQLSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLSanPhamMouseClicked
        CardLayout cl = (CardLayout) pnlMainContent.getLayout();
        cl.show(pnlMainContent, "pnlQuanLySanPham");
        ((poly.cinema.ui.manager.QuanLySanPham) pnlQuanLySanPham).open();
    }//GEN-LAST:event_lblQLSanPhamMouseClicked

    private void lblQLPhimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLPhimMouseClicked
        CardLayout cl = (CardLayout) pnlMainContent.getLayout();
        cl.show(pnlMainContent, "pnlQuanLyPhim");
        ((poly.cinema.ui.manager.QuanLyPhim) pnlQuanLyPhim).open();
    }//GEN-LAST:event_lblQLPhimMouseClicked

    private void lblXemLichChieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXemLichChieuMouseClicked
        CardLayout cl = (CardLayout) pnlMainContent.getLayout();
        cl.show(pnlMainContent, "pnlXemLichChieu");
        ((poly.cinema.ui.manager.XemLichChieu) pnlXemLichChieu).open();
    }//GEN-LAST:event_lblXemLichChieuMouseClicked

    private void lbldoimkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldoimkMouseClicked
        CardLayout cl = (CardLayout) pnlMainContent.getLayout();
        cl.show(pnlMainContent, "pnlDoiMatKhau");
        ((poly.cinema.ui.DoiMatKhau) pnlDoiMatKhau).open();
    }//GEN-LAST:event_lbldoimkMouseClicked

    private void lbldãnguatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldãnguatMouseClicked
        logout();
    }//GEN-LAST:event_lbldãnguatMouseClicked

    private void lblQLPhongChieu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLPhongChieu1MouseClicked
       CardLayout cl = (CardLayout) pnlMainContent.getLayout();
        cl.show(pnlMainContent, "pnlLoaighe");
        ((poly.cinema.ui.manager.LoaiGheJpanel) pnlLoaighe).open();
    }//GEN-LAST:event_lblQLPhongChieu1MouseClicked

    private void lblQLPhongChieu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLPhongChieu2MouseClicked
        CardLayout cl = (CardLayout) pnlMainContent.getLayout();
        cl.show(pnlMainContent, "pnlLoaiPhim");
        ((poly.cinema.ui.manager.LoaiPhimPanel) pnlLoaiPhim).open();
    }//GEN-LAST:event_lblQLPhongChieu2MouseClicked
    private void addHoverEffectToPanelLabels(JPanel panel) {
        for (Component comp : panel.getComponents()) {
            if (comp instanceof JLabel lbl) {

                lbl.setOpaque(true); // Bắt buộc để hiện màu nền
                lbl.setBackground(Color.LIGHT_GRAY);
                lbl.setForeground(Color.BLACK);
                lbl.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Tay trỏ

                lbl.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseEntered(MouseEvent e) {
                        lbl.setBackground(Color.BLUE);
                        lbl.setForeground(Color.WHITE);
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
                        lbl.setBackground(Color.LIGHT_GRAY);
                        lbl.setForeground(Color.BLACK);
                    }
                });
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FCinema_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FCinema_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FCinema_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FCinema_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FCinema_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBanVe;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblLichSuBanHang;
    private javax.swing.JLabel lblQLDoanhthu;
    private javax.swing.JLabel lblQLGhe;
    private javax.swing.JLabel lblQLHoaDon;
    private javax.swing.JLabel lblQLNHANVIEN;
    private javax.swing.JLabel lblQLPhim;
    private javax.swing.JLabel lblQLPhongChieu;
    private javax.swing.JLabel lblQLPhongChieu1;
    private javax.swing.JLabel lblQLPhongChieu2;
    private javax.swing.JLabel lblQLSanPham;
    private javax.swing.JLabel lblXemLichChieu;
    private javax.swing.JLabel lbldoimk;
    private javax.swing.JLabel lbldãnguat;
    private javax.swing.JLabel lblsuatchieu;
    private javax.swing.JPanel pnlBanHang;
    private javax.swing.JPanel pnlBanSanPham;
    private javax.swing.JPanel pnlBanVe;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlChonPhim;
    private javax.swing.JPanel pnlDoiMatKhau;
    private javax.swing.JPanel pnlLichSuBanHang;
    private javax.swing.JPanel pnlLoaiGhe;
    private javax.swing.JPanel pnlLoaiPhim;
    private javax.swing.JPanel pnlLoaighe;
    private javax.swing.JPanel pnlMainContent;
    private javax.swing.JPanel pnlManager;
    private javax.swing.JPanel pnlQuanLyGhe;
    private javax.swing.JPanel pnlQuanLyHoaDon;
    private javax.swing.JPanel pnlQuanLyNhanVien;
    private javax.swing.JPanel pnlQuanLyPhim;
    private javax.swing.JPanel pnlQuanLyPhongChieu;
    private javax.swing.JPanel pnlQuanLySanPham;
    private javax.swing.JPanel pnlQuanLySuatChieu;
    private javax.swing.JPanel pnlThongKeDoanhThu;
    private javax.swing.JPanel pnlTrangchu;
    private javax.swing.JPanel pnlXemLichChieu;
    private javax.swing.JPanel pnlchonGhe;
    // End of variables declaration//GEN-END:variables

    @Override
    public void init() {
        this.setIconImage(XIcon.getIcon("logonho.png").getImage());

        this.showWelcomeJDialog(this);
        this.showLoginJDialog(this);

        lblFullname.setText(XAuth.user.getTenNd());
        if (!XAuth.user.isVai_tro()) {
            pnlCenter.remove(pnlManager);
        }
//        if (XAuth.user.isVai_tro()) {
//            pnlCenter.remove(pnlManager1);
//        } 
    }

    private void logout() {
        if (XDialog.confirm("Bạn có chắc chắn muốn đăng xuất không?")) {
            this.dispose();
            if (XAuth.user != null) {
                FCinema_Frame main = new FCinema_Frame();
                lblFullname.setText(XAuth.user.getTenNd());
                if (!XAuth.user.isVai_tro()) {
                    pnlCenter.remove(pnlManager);
                }
                main.setVisible(true);
            }
        }
    }

    @Override
    public void exit() {
        FCinema_Controller.super.exit(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void showJDialog(JDialog dialog) {
        FCinema_Controller.super.showJDialog(dialog); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void showWelcomeJDialog(JFrame frame) {
        FCinema_Controller.super.showWelcomeJDialog(frame); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void showLoginJDialog(JFrame frame) {
        FCinema_Controller.super.showLoginJDialog(frame); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }
}
